# Generated by Django 4.0.4 on 2022-05-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0012_remove_plot_connect_point_plot_connect_coordinate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='connect_plot',
        ),
        migrations.AlterField(
            model_name='plot',
            name='connect_coordinate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
